var buttonColors = ["red", "blue", "green", "yellow"];

var randomChosenColour;
var gamePattern=[];
var userClickedPattern=[];
var gameStarted = false;
var level  = 0;

// this functions tells us about the sequence of the color that we will be playing
function nextSequence(){
    
    var randomNumber = Math.floor(Math.random()*4);
    
    // this has the random color that has been generated by the nextsequence
    randomChosenColour = buttonColors[randomNumber];

    // saving the color of the game in the gamepattern 
    gamePattern.push(randomChosenColour);
    
    $("#"+buttonColors[randomNumber]).fadeIn(100).fadeOut(100).fadeIn(100);
    
    
    // this plays the audio whenever a nextsequence selects a random color with the audio that is assigned to it
    playSound(randomChosenColour);
    
    
    level++;
    $("h1").text("Level "+ level);
    
}

// this function checks the answer every time user clicks the button
// however the current level is the amount of times user has clicked on the button
//that is why it only checks the length of the array that user clicked 
function checkAnswer(currentLevel){
    console.log("Check Answer was called");
    for (let index = 0; index < currentLevel; index++) {
        if(gamePattern[index]!=userClickedPattern[index]){    
            $("body").addClass("game-over") 
            setTimeout(function() {
                $("body").removeClass("game-over") 
            },100); 
            playSound("wrong")   
        gameOver();
        return;
        }
    }
    
    //  this if statement will only work if the amount of clicked that user done is equal to 
    // the last level he was at
    if(currentLevel==level){
        userClickedPattern=[];
        setTimeout(function() {
            nextSequence();    
        },1000);    
    }
    
}

// this function resets the values back to zero for everything
function gameOver(){
    userClickedPattern=[];
    gamePattern=[];
    level=0;
    $("h1").text("Game Over Press any button to play again");
    gameStarted =false;
}

//play sound function 
function playSound(soundColor){
    var audio = new Audio("sounds/"+soundColor+".mp3");
    audio.play();
}


// this function will animate the button that has been pressed by the user
function animatePress(pressedButtonColour){
$("#"+pressedButtonColour).addClass("pressed");
setTimeout(function() {
    $("#"+pressedButtonColour).removeClass("pressed");
},100);
}

//using Jquery to see which button is pressed
$(".btn").click(function (){
       var userChosenColour=this.id;
       userClickedPattern.push(userChosenColour);
       animatePress(userChosenColour);
       playSound(userChosenColour);
       
       
        checkAnswer(userClickedPattern.length);

     
})

// this is to  detect when the keyboard is presesd
$(document).keypress(function(event){
    if(!gameStarted){
        nextSequence();
        gameStarted = true;
        $("h1").text("Level "+level);
    }
})
